version: '3'
services:
  web:
    build: .
    command: bash -c "python ./market/manage.py makemigrations && python ./market/manage.py migrate && python ./market/manage.py collectstatic --noinput && gunicorn -c config/gunicorn/conf.py --bind :8000 --chdir market market.wsgi:application && celery -A market worker -l info"
    depends_on:
      - database
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - database_network
      - nginx_network
      - rabbitmq_network

  database:
    image: postgres:13-alpine
    volumes:
      - database_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database_env
    networks:
      - database_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq_network
    volumes:
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./logs/rabbitmq:/var/log/rabbitmq

  nginx:
    image: nginx:1.13
    ports:
      - "8000:80"
    depends_on:
      - web
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge

volumes:
  database_volume:
  static:
  media: